#Server
server.port=8080

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://db:5432/miniBlog
spring.datasource.username=min
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.schema-locations=classpath:schema.sql


# ??? ??????? ?????????? db
# docker run -d --name db -e POSTGRES_DB=miniBlog -e POSTGRES_USER=min -e POSTGRES_PASSWORD=1234 -p 5432:5432 postgres