DROP TABLE IF EXISTS users, posts;

CREATE TABLE IF NOT EXISTS users (
     id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
     email                    VARCHAR(255) NOT NULL CHECK (email <> ''),
     username                 VARCHAR(50) NOT NULL CHECK (username <> ''),
     created_at               TIMESTAMP NOT NULL DEFAULT now()
     );

CREATE TABLE IF NOT EXISTS posts (
     id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
     title                    VARCHAR(512) NOT NULL CHECK (title <> ''),
     content                  VARCHAR(1000) NOT NULL CHECK (content <> ''),
     author_id                BIGINT REFERENCES users (id) ON DELETE CASCADE,
     created_at               TIMESTAMP NOT NULL DEFAULT now(),
     updated_at               TIMESTAMP NOT NULL DEFAULT now()
     );