DROP TABLE IF EXISTS users, posts, comments, likes

CREATE TABLE IF NOT EXISTS users (
     id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
     email                    VARCHAR(255) NOT NULL CHECK (email <> ''),
     username                 VARCHAR(50) NOT NULL CHECK (username <> ''),
     password                 VARCHAR(255) NOT NULL CHECK (password <> ''),
     created_at               TIMESTAMP NOT NULL DEFAULT now(),
     updated_at               TIMESTAMP NOT NULL DEFAULT now()
     );

CREATE TABLE IF NOT EXISTS posts (
     id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
     title                    VARCHAR(255) NOT NULL CHECK (title <> ''),
     content                  VARCHAR(512) NOT NULL CHECK (content <> ''),
     author_id                BIGINT REFERENCES users (id) ON DELETE CASCADE,
     created_at               TIMESTAMP NOT NULL DEFAULT now(),
     updated_at               TIMESTAMP NOT NULL DEFAULT now()
     );

CREATE TABLE IF NOT EXISTS comments (
     id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
     content                  VARCHAR(255) NOT NULL CHECK (content <> ''),
     user_id                  BIGINT REFERENCES users (id) ON DELETE CASCADE,
     post_id                  BIGINT REFERENCES posts (id) ON DELETE CASCADE,
     created_at               TIMESTAMP NOT NULL DEFAULT now()
     );

CREATE TABLE IF NOT EXISTS likes (
     id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
     user_id                  BIGINT REFERENCES users (id) ON DELETE CASCADE,
     post_id                  BIGINT REFERENCES posts (id) ON DELETE CASCADE
     );
     CONSTRAINT unique_like UNIQUE (user_id, post_id)
